### ISSUE TITLE
逍遥行似乎很新，在论坛上有相应的帖子吗？

### ISSUE THREAD

**Issue by sefeng211** [zixijian/tt#1]
感谢更新tintin版的逍遥行。
我试过几个地方，暂时没有什么大问题。
但有时候gt here不正确，需要手动走到相应的地点，再寻路。

论坛上tintin逍遥行的帖子都很老了，如果这个版本也在在论坛上有的话，可以帮助更多的tintin用户。

**Comment by zixijian** [comment]
可以自行转载、修改，原信息不要删除。

我跟着最新版本走，后期转utf8、Go-Mud。
